name: Create-NuGet-iOS

on:
  push:
    branches: [ use_github_actions ]
  pull_request:
    branches: [ use_github_actions ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Select Xcode version
      run: |
        sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
        xcodebuild -version
    - name: Setup Xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: 6.12 # specify version in '<major>.<minor>' format
        xamarin-ios-version: 14.0 # specify version in '<major>' format
        xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
        xamarin-android-version: 11.2 # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
        xcode-version: 12
    - uses: actions/checkout@v2
    - name: Create NuGet package
      run: |
        cd ${{ github.workspace }}/iOS/ExposureNotification
        msbuild -p:Configuration=Release -t:pack
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuget_ios
        path: ${{ github.workspace }}/iOS/ExposureNotification/source/bin/Release/*.nupkg
        retention-days: 14
