name: .NET

on:
  push:
    branches: [ use_github_actions ]
  pull_request:
    branches: [ use_github_actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build ExposureNotification Android
      run: |
        cd ${{ github.workspace }}/Android/ExposureNotification
        dotnet new tool-manifest
        dotnet cake
